<footer>
  <p>OPALE version Develop 2026/04/15 — <a href="mailto:ha.lamot.pro@gmail.com">Hugues-Arnaud LAMOT</a>
    (<a href="https://www.linkedin.com/in/hugues-arnaud-lamot/" target="_blank" rel="noopener">
      <img
          src="https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png"
          alt="LinkedIn"
          width="24"
          height="24">
    </a>)
  </p>
</footer>