<?php
    $currentPage = 'feature';
 ?>

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>VSM - Jira</title>
    <link rel="stylesheet" href="/style.css">
</head>

<body>
    <?php
        include __DIR__ . '/components/topNavigation.phtml';
    ?>

    <div class="card">
        <h1>Value Stream Mapping - Feature Jira</h1>

        <p>Analyse d'une Feature Jira à venir.</p>
    </div>
</body>