<?php

/** @var \App\Controller\VersionController $this */
/** @var \App\View\VersionView $view */
/** @var \App\Model\Issue $issue */
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>VSM - Jira</title>
    <link rel="stylesheet" href="/style.css">
</head>

<body>
    <?php if ($this->getIsDemo()): ?>
        <div style="color:red;font-weight:bold;">
            ⚠️ Mode DÉMO activé dans .env => Vérification SSL <u>désactivée</u> ⚠️
        </div>
    <?php endif; ?>

    <div class="card">
        <h1>Value Stream Mapping - Version Jira</h1>

        <?php include __DIR__ . '/form/selectJiraProjectAndVersions.phtml'; ?>
        <form method="POST" action="/version">
            <label>Ou directement par FixVersion ID :</label>
            <input type="text" name="fixVersionId" required placeholder="Indiquer l'ID de la version Jira à utiliser (fixVersion)">
            <button type="submit">OK</button>
        </form>
    </div>

    <?php include __DIR__ . '/components/errorMessage.phtml'; ?>

    <?php if ($view): ?>
        <div class="card">
            <h2>
                <a href="<?= $view->getVersionUrl(); ?>" target="_blank">
                    <?= $view->getVersionName(); ?> (<?= 'ID ' . $view->getVersionId(); ?>)
                </a>
            </h2>

            <p style="margin-top: 12px; color: var(--muted);">
                <?= $view->getVersionDescription(); ?>
            </p>

            <div class="meta">
                <!-- Infos version -->
                <div class="meta-line meta-line-info">
                    <span>📅 Date de démarrage : <?= $view->getVersionStartDate() ?? '—'; ?></span>
                    <span>🎯 Date cible de livraison : <?= $view->getVersionReleaseDate() ?? '—'; ?></span>

                    <?php if ($view->isVersionOverdue()): ?>
                        <span class="badge red">🕗Deadline dépassée</span>
                    <?php endif; ?>

                    <?php if ($view->isVersionReleased()): ?>
                        <span class="badge green">Statut : Terminée 🚀</span>
                    <?php else: ?>
                        <span class="badge orange">Statut : En cours</span>
                    <?php endif; ?>
                </div>

                <!-- Métriques -->
                <div class="meta-line meta-line-metrics">
                    <!-- Lead Time -->
                    <div class="metric">
                        <span class="metric-title">📦 <b>Lead Time</b> <em>(jours calendaires Création -> Terminé)</em></span>
                        <span>Total : <strong><?= $view->getTotalLeadTime(); ?> jours</strong></span>
                        <span>Moyen : <strong><?= $view->getAverageLeadTime(); ?> jours /ticket</strong></span>
                    </div>

                    <!-- Cycle Time -->
                    <div class="metric">
                        <span class="metric-title">🛠️ <b>Cycle Time</b> <em>(jours ouvrés En cours -> Terminé)</em></span>
                        <span>Total : <strong><?= $view->getTotalCycleTime(); ?> jours</strong></span>
                        <span>Moyen : <strong><?= $view->getAverageCycleTime(); ?> jours /ticket</strong></span>
                    </div>

                    <!-- Time Breakdown -->
                    <div class="metric">
                        <span class="metric-title">🧮 <b>Temps par phase</b></span>
                        <span>🧠 Affinage : <strong><?= $view->getTotalTimeSpentInRefinement(); ?> jours.</strong> <em>Moyenne : <strong><?= $view->getAverageTimeSpentInRefinement(); ?> jours /ticket.</strong></em></span>
                        <span>⚙️ Réal + Qualif : <strong><?= $view->getTotalTimeSpentInSprint(); ?> jours.</strong> <em>Moyenne : <strong><?= $view->getAverageTimeSpentInSprint(); ?> jours /ticket.</strong></em></span>
                        <span>❓ Autre : <strong><?= $view->getTotalTimeSpentInOther(); ?> jours.</strong> <em>Moyenne : <strong><?= $view->getAverageTimeSpentInOther(); ?> jours /ticket.</strong></em></span>
                    </div>
                </div>
            </div>
        </div>

        <div class="timeline-grid">
            <!-- Timeline par statut -->
            <?php include __DIR__ . '/metrics/timelineChart.phtml'; ?>
        </div>

        <div class="card">
            <h2><?= $view->getIssuesCount(); ?> tickets rattachés à cette version :</h2>
            <?php include __DIR__ . '/issuesList.phtml'; ?>
        </div>

    <?php endif; ?>

</body>

</html>